# Generated by Django 3.1.2 on 2020-10-14 20:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionbox', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.ManyToManyField(blank=True, related_name='correct_answers', to=settings.AUTH_USER_MODEL),
        ),
    ]
